#versao do docker compose
version: '3'

#servicos que iremos subir
services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  app:
    build: 
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 50s docker-entrypoint.sh
    command: node index.js
    networks:
      - node-network
    tty: true
    volumes:
      - ./node:/usr/src/app
    depends_on:
      - db

  nginx:
    restart: always
    build: 
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80" 
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge